version: '3.9'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Rojas#$70
      - DB_NAME=rukanas_web
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rojas#$70
      MYSQL_DATABASE: rukanas_web
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
